Desktop/github/rentify/rentify/edit/urls.py
from django.urls import path
from.import views
app_name='edit'
urlpatterns=[
    path('add/',views.add,name='add'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

]

Desktop/github/rentify/rentify/login/urls.py
from django.urls import path

from.import views
app_name='login'
urlpatterns=[
    path('registration/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('seller/',views.seller,name='seller'),
    path('',views.login_user,name='login')
]

Desktop/github/rentify/rentify/rent/urls.py
from django.urls import path
from . import views
app_name='rent'
urlpatterns=[
    path('',views.home,name="home"),
    path('search/',views.SearchResult,name='searchresult'),
    path('property/<int:id>/',views.property,name="property"),
    path('filter/<str:place>/',views.filter,name="property_detail")
]

Desktop/github/rentify/rentify/rentify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('edit/',include('edit.urls')),
    path('',include('rent.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

Desktop/github/rentify/rentify/edit/models.py
from django.db import models

# Create your models here.

Desktop/github/rentify/rentify/login/models.py
from django.db import models

# Create your models here.

Desktop/github/rentify/rentify/rent/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
class Property(models.Model):
    place=models.CharField(max_length=200)
    area=models.CharField(max_length=200)
    img=models.ImageField(upload_to='image')
    bedrooms=models.IntegerField()
    bathrooms=models.IntegerField()
    hospitals=models.IntegerField()
    colleges=models.IntegerField()
    added_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


    def __str__(self):
        return self.place

Desktop/github/rentify/rentify/edit/forms.py
from django import forms
from rent.models import Property


class PropertyForm(forms.ModelForm):
    class Meta:
        model=Property
        fields=['place','area','img','bedrooms','bathrooms','hospitals','colleges']

Desktop/github/rentify/rentify/edit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rent.models import Property
from.forms import PropertyForm
# Create your views here.
def add(request):
    if request.method == 'POST':
        place = request.POST.get('place')
        area = request.POST.get('area')
        bedrooms = request.POST.get('bedrooms')
        bathrooms = request.POST.get('bathrooms')
        hospitals = request.POST.get('hospitals')
        img = request.FILES.get('img')
        colleges=request.POST.get('colleges')
        user = request.user
        property = Property(place=place, area=area, bedrooms=bedrooms, bathrooms=bathrooms, hospitals=hospitals, img=img, colleges=colleges,added_by=user)
        property.save()
        return redirect('rent:home')
    return render(request, 'add.html')

def update(request,id):
    property=Property.objects.get(id=id)
    form = PropertyForm(request.POST,request.FILES, instance=property)
    if request.method == 'POST':
            if form.is_valid():
                form.save()
                return redirect('rent:home')
    return render(request,'update.html',dict(form=form))

def delete(request,id):
    property = get_object_or_404(Property, id=id)
    property.delete()
    return redirect('/')

Desktop/github/rentify/rentify/login/views.py
from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth import get_user_model, authenticate, login
from django.shortcuts import render, redirect


# Create your views here.
def seller(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('Password')
        user=auth.authenticate(username=username,password=password)
        # if user is not None and not user.is_administrator:
        if user is not None and user.is_staff:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credntials')
            return redirect('login:seller')

    return render(request,'login.html',{'user_type':'Seller'})

def login_user(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('Password')
        user=auth.authenticate(username=username,password=password)
        # if user is not None and not user.is_administrator:
        if user is not None and not user.is_staff:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credntials')
            return redirect('login:login')

    return render(request,'login.html',{'user_type':'buyer'})
def register(request):
    User = get_user_model()
    if request.method=='POST':
        username=request.POST.get('username')
        fname=request.POST.get('fname')
        lname=request.POST.get('lname')
        email=request.POST.get('email')
        password=request.POST.get('psw')
        cpassword=request.POST.get('psw-repeat')
        is_seller = request.POST.get('is_seller') == 'on'

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username taken')
                return redirect('login:register')
            else:
                if is_seller:
                    user=User.objects.create_user(username=username,password=password,first_name=fname,last_name=lname,email=email,is_staff=True)
                else:
                    user=User.objects.create_user(username=username,password=password,first_name=fname,last_name=lname,email=email,is_staff=False)


                user.save()
                # Authenticate the user
                return redirect("login:login")
        else:
            messages.info(request,'password not matching')
            return redirect("login:register")

    else:
        return render(request,"registration.html")

def logout(request):
    auth.logout(request)

    return redirect(settings.LOGOUT_REDIRECT_URL)

Desktop/github/rentify/rentify/rent/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from.models import Property
# Create your views here.
def home(request):
    properties=None
    user=request.user
    if user.is_authenticated:
        if user.is_staff:
            properties = Property.objects.filter(added_by=user.id)

            paginator = Paginator(properties, 3)
            try:
                page = int(request.GET.get('page', '1'))
            except:
                page = 1
            try:
                properties = paginator.page(page)
            except (EmptyPage, InvalidPage):
                properties = paginator.page(paginator.num_pages)
        else:
            properties = Property.objects.all()
            paginator = Paginator(properties, 3)
            try:
                page = int(request.GET.get('page', '1'))
            except:
                page = 1
            try:
                properties = paginator.page(page)
            except (EmptyPage, InvalidPage):
                properties = paginator.page(paginator.num_pages)


    return render(request, 'home.html', {'properties': properties})
def filter(request,place):
    user=request.user
    properties = Property.objects.filter(place=place)
    context = {'properties': properties}
    return render(request, 'filter.html', context)

def SearchResult(request):
    property=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        property=Property.objects.all().filter(Q(place__contains=query))
    return render(request,'filter.html',{'query':query,'properties':property})

def property(request,id):
    try:
        property = Property.objects.get(id=id)
    except Exception as e:
        raise e
    return render(request, 'property.html', {'property': property})

Desktop/github/rentify/rentify/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Place</label>
    <input type="text" class="form-control" name="place" id="exampleInputEmail1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Area</label>
    <input type="text" class="form-control" name="area" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="ex" class="form-label">Bedrooms</label>
    <input type="number" class="form-control"  name="bedrooms" id="ex">
  </div>
 <div class="mb-3">
    <label for="ex" class="form-label">Bathrooms</label>
    <input type="number" class="form-control"  name="bathrooms" id="ex">
  </div>

  <div class="mb-3">
    <label for="exa" class="form-label">Image</label>
    <input type="file" class="form-control"  name="img" id="exa">
  </div>
<div class="mb-3">
    <label for="exa2" class="form-label">Hospitals</label>
    <input type="number" class="form-control"  name="hospitals" id="exa2">
  </div>
    <div class="mb-3">
    <label for="exa3" class="form-label">Colleges</label>
    <input type="number" class="form-control"  name="colleges" id="exa3">
  </div>

  <button style="width:100%" type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

Desktop/github/rentify/rentify/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <Link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <script src="https://kit.fontawesome.com/c386a9710a.js" crossorigin="anonymous"></script>
     <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>

{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Desktop/github/rentify/rentify/templates/filter.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
{% if properties %}
    {% for property in properties %}
        <div class="my_bottommargin card-container col-sm-12  col-md-4 col-lg-4">
        <div class="card text-center" style="min-width: 18rem;">
            <a href="#"><img class="card-img-top my-image" height="300px" src="{{property.img.url}}" alt="property image"></a>
         <div class="card-body">
            <h5 class="card-title">{{property.place}}</h5>
             <ul class="list-group list-group-flush">
    <li class="list-group-item">{{property.area}}</li>
    <li class="list-group-item">Bedrooms:{{property.bedrooms}}</li>
    <li class="list-group-item">Bathrooms:{{property.bathrooms}}</li>
                 <li class="list-group-item">Hospitals Nearby:{{property.hospitals}}</li>
                 <li class="list-group-item">Colleges Nearby:{{property.colleges}}</li>
  </ul>
              <a href="{% url 'rent:property' id=property.id %}" class="btn btn-success">click me</a>
            </div>
        </div>
        </div>
    {% endfor %}

{% else %}
<p style="color:red;font-size:20px" class="text-center">no properties available!!</p>
{% endif %}
</div>

{% endblock %}

Desktop/github/rentify/rentify/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; Rentify pvt limited.All Rights Reserved</p>
</div>

Desktop/github/rentify/rentify/templates/header.html
{% load static %}
<header>
    <center>
        <img src="{% static 'img/rentifylogo.jpg' %}" alt="logo" width="200px" height="200px"></a>
    </center>
</header>

Desktop/github/rentify/rentify/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
property
{% endblock %}
{% block content %}
<h1 class="text-center my_title">Rentify</h1>
        <div>
             <img class="my_image my_image_padding" src="{% static 'img/rentbanner.jpg' %}" alt="banner" width="100%">
        </div>
            <br>
        <div>
            <p class="text-justify">Welcome to Rentify, your ultimate destination for all your rent details! Whether you're a tenant searching
                for the perfect property or a landlord managing rentals, our platform provides comprehensive information to simplify your renting
                experience. From property listings and rental rates to tips on navigating the rental market, we've got you covered. Stay informed, make informed decisions, and streamline your renting process with Rentify.</p>

        </div>
<div class="row">

    {% for property in properties %}
        <div class="my_bottommargin card-container col-sm-12  col-md-4 col-lg-4">
        <div class="card text-center" style="min-width: 18rem;">
            <a href="#"><img class="card-img-top my-image" height="300px" src="{{property.img.url}}" alt="property image"></a>
         <div class="card-body">
            <h5 class="card-title">{{property.place}}</h5>
             <ul class="list-group list-group-flush">
    <li class="list-group-item">{{property.area}}</li>
    <li class="list-group-item">Bedrooms:{{property.bedrooms}}</li>
    <li class="list-group-item">Bathrooms:{{property.bathrooms}}</li>
                 <li class="list-group-item">Hospitals Nearby:{{property.hospitals}}</li>
                 <li class="list-group-item">Colleges Nearby:{{property.colleges}}</li>
  </ul>
             {% if user.is_staff %}
             <a href="{% url 'edit:update' id=property.id %}" class="btn btn-warning">update</a>
             <a href="{% url 'edit:delete' id=property.id %}" class="btn btn-danger">delete</a>
             {% else %}
             <a href="{% url 'rent:property' id=property.id %}" class="btn btn-success">click me</a>
             {% endif %}
            </div>
        </div>
        </div>
    {% endfor %}


</div>
 <div class="mxauto">
        {% if properties.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in properties.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
      {% endif %}
    </div>
{% endblock %}

Desktop/github/rentify/rentify/templates/login.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="{% static 'css/custom2.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
  </head>
  <body>
 <div style="position:absolute;top:30px;right:30px;">
    <a class="btn btn-primary" href="{% url 'login:seller' %}">Login as Seller</a>
    <a class="btn btn-primary" href="{% url 'login:login' %}">Login as Buyer</a>
  </div>


    <div class="container">
      <div class="wrapper">
        {% if user_type == 'Seller' %}
        <div class="title"><span>Seller Login</span></div>
        {% else %}
        <div class="title"><span>Buyer Login</span></div>
        {% endif %}
        <form action="" method="post">
          {% csrf_token %}
          <div class="row">
            <i class="fas fa-user"></i>
            <input type="text" placeholder="username" name="username" required>
          </div>
          <div class="row">
            <i class="fas fa-lock"></i>
            <input type="password" placeholder="Password" name="Password" required>
          </div>
          <div class="row button">
            <input type="submit" value="Login">
          </div>
          <div class="signup-link">Not a member? <a href="{% url 'login:register' %}">Signup now</a></div>
        </form>
      </div>
          {% for msg in messages %}
  <P class="text-center" style="color:red;font-size:20px;">{{msg}}!!</p>
  {% endfor %}
    </div>
  <script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

Desktop/github/rentify/rentify/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  {% if user.is_authenticated %}
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'edit:add' %}">Add Post</a>
        </li>
        {% endif %}
        {% if not user.is_staff %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Filter
          </a>
          <ul class="dropdown-menu">
              {% for place in links %}
            <li><a class="dropdown-item" href="{% url 'rent:property_detail' place=place %}">{{place}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% endif %}
      </ul>
       <form class="d-flex" role="search" action="{% url 'rent:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search by place" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <div class="d-flex justify-content-end">
    <form class="d-flex" action="{% url 'login:logout' %}" method="get" >
      <button class="btn btn-primary" style="margin-left: 10px;" type="submit">logout</button>
    </form>
      </div>


    </div>
  </div>
  {% else %}
<div class="container-fluid">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="#">Home</a>
    </li>
  </ul>
     <!-- Center the MovieZone heading -->
  <div class="d-flex justify-content-end">
    <form class="d-flex" action="{% url 'login:login' %}" method="get" >
      <button class="btn btn-primary" type="submit">Sign in</button>
    </form>
    <form class="d-flex" action="{% url 'login:register' %}" method="get" style="margin-left: 10px;">
      <button class="btn btn-primary" type="submit">Sign up</button>
    </form>
  </div>
</div>
  {% endif %}
</nav>

Desktop/github/rentify/rentify/templates/property.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

        property
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{property.img.url}}" alt="property image" width="488" height="488">
        </div>
    </div>


    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title" style="text-transform:uppercase;">{{property.place}}</h1>
            <p><b>Area</b>: {{property.area}}</p>
            <p><b>Bedrooms</b>: {{property.bedrooms}}</p>
            <p><b>Bathrooms</b>: {{property.bathrooms}}</p>
            <p><b>Hospitals Nearby</b>: {{property.hospitals}}</p>
            <p><b>Colleges Nearby</b>: {{property.colleges}}</p>
            <p><b style="color:red;"><u>Seller Details</u></b> </p>
            <p><b>Seller Name</b>:{{property.added_by}}</p>
            <p><b>email</b>:{{property.added_by.email}}</p>


</div>
    </div>

</div>

{% endblock %}

Desktop/github/rentify/rentify/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom3.css' %}">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<style>

</style>
</head>
<body>
<div class="form-container">
<form action="" method="post">
  {% csrf_token %}
  <div class="container">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="email"><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="username" id="email" required>

    <label for="fname"><b>Firstname</b></label>
    <input type="text" placeholder="Enter firstname" name="fname" id="fname" required>
    <label for="lname"><b>Lastname</b></label>
    <input type="text" placeholder="Enter lastname" name="lname" id="lname" required>
    <label for="mail"><b>email</b></label>
    <input type="text" placeholder="Enter mail id" name="email" id="mail" required>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>

        <label for="id_is_seller">Are you a seller?</label>
    <input type="checkbox" name="is_seller" id="id_is_seller"><br>
  <hr>

    <button type="submit" class="registerbtn">Register</button>
  </div>
  <div class="container signin">
    <p>Already have an account? <a href="{% url 'login:login' %}">Sign in</a>.</p>
  </div>
</form>
</div>
{% for msg in messages %}
<p style="color:red;font-size:30px;" class="text-center">{{msg}}!!</p>
{% endfor %}
</body>
</html>

Desktop/github/rentify/rentify/templates/update.html
{% extends 'base.html' %}
{% block title %}update{% endblock %}
{% block content %}
<div class="form-container">
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   {{form.as_p}}
    <input type="submit" value="Save">
</form>
</div>
{% endblock %}